"""Initial migration - users and escritorios

Revision ID: 78d7cf7f2ecc
Revises: f8ec538bd907
Create Date: 2025-11-08 00:06:28.074584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d7cf7f2ecc'
down_revision = 'f8ec538bd907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
