"""Initial migration

Revision ID: f8ec538bd907
Revises: 81d69962e6e9
Create Date: 2025-11-08 00:03:46.970483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ec538bd907'
down_revision = '81d69962e6e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
